include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem-dongle-left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem-dongle-right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact-name: totem-dongle-screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: totem-settings-reset
